apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grocery-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kavirajkv/grocery-cd.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: grocery
  syncPolicy:
    syncOptions:
    - CreateNamesapce=true
    automated:
      selfHeal: true
      prune: true


      